/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.Customer;

import javax.swing.JLabel;
import javax.swing.JOptionPane;
import View.Customer.CustomerDisplay;
import javax.swing.JFrame;
//import static View.CustomerDisplay.openMenu;
//import static View.CustomerDisplay.addNewProduct;
import View.Customer.CustomerDisplay;
import static Controller.Customer.HandleProducts.getProducts;
import java.util.Map;
import static Controller.Customer.HandleProducts.Products;
import static View.Customer.CustomerDisplay.numberItemCart;
import View.Customer.Notification.Message;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.BorderFactory;

/**
 *
 * @author ngocn
 */
public class Order extends javax.swing.JPanel {

    /**
     * Creates new form Product
     */
    public Order() {
        initComponents();
        BorderFactory.createMatteBorder(2, 0, 0, 0, Color.BLACK);
        
        setPreferredSize(new Dimension(610, 122));
    }

    public JLabel getProductImg() {
        return productImg;
    }

    public void setQuantity(String quantity) {
        this.quantity.setText("x" + quantity);
    }

    public void setSize(String size) {
        this.size.setText("Size: " + size + ".");
    }

    public void setTopping(String topping) {
        if (topping.equals("null")) {
            this.topping.setText("Không có topping thêm.");
        } else {
            this.topping.setText("Topping thêm: " + topping + ".");
        }
    }

    public void setTextProductName(String productName) {
        this.productName.setText(productName);
    }

    public void setTextProductPrice(String productPrice) {
        this.productPrice.setText("₫" + productPrice);
    }

    public void setImage(String imgPath) {
        this.productImg.setToolTipText(imgPath);
        this.productImg.setIcon(new javax.swing.ImageIcon(getClass().getResource(imgPath)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        productImg = new javax.swing.JLabel();
        productPrice = new javax.swing.JLabel();
        productName = new javax.swing.JLabel();
        quantity = new javax.swing.JLabel();
        size = new javax.swing.JLabel();
        topping = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        productImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/products/cacao-sua-special-43851616127873.JPG"))); // NOI18N

        productPrice.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        productPrice.setForeground(new java.awt.Color(27, 43, 32));
        productPrice.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        productPrice.setText("₫23000");

        productName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        productName.setForeground(new java.awt.Color(0, 0, 0));
        productName.setText("Trà sữa Truyền Thống");

        quantity.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        quantity.setForeground(new java.awt.Color(0, 0, 0));
        quantity.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        quantity.setText("x1");

        size.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        size.setForeground(new java.awt.Color(153, 153, 153));
        size.setText("Size: Nhỏ");

        topping.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        topping.setForeground(new java.awt.Color(153, 153, 153));
        topping.setText("Topping:");
        topping.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toppingMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(productImg, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(productName)
                        .addContainerGap(282, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(productPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(size, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(topping, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(productName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(size)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(topping)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(quantity)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(productPrice))
                    .addComponent(productImg, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void toppingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toppingMouseClicked
        JFrame notification = new JFrame();
        notification.setAlwaysOnTop(true);
//        JOptionPane.showMessageDialog(notification, topping.getText(), "Mô tả sản phẩm", JOptionPane.PLAIN_MESSAGE);
        Message message = new Message(notification, true);
        message.setTitle("Thông tin sản phẩm");
        message.setContent(topping.getText());
        message.setVisible(true);
    }//GEN-LAST:event_toppingMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel productImg;
    private javax.swing.JLabel productName;
    private javax.swing.JLabel productPrice;
    private javax.swing.JLabel quantity;
    private javax.swing.JLabel size;
    private javax.swing.JLabel topping;
    // End of variables declaration//GEN-END:variables
}
