/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.Customer;

import javax.swing.JLabel;
import javax.swing.JOptionPane;
import View.Customer.CustomerDisplay;
import javax.swing.JFrame;
//import static View.CustomerDisplay.openMenu;
//import static View.CustomerDisplay.addNewProduct;
import View.Customer.CustomerDisplay;
import static Controller.Customer.HandleProducts.getProducts;
import java.util.Map;
import static Controller.Customer.HandleProducts.Products;
import static View.Customer.CustomerDisplay.numberItemCart;
import View.Customer.Notification.Message;
import java.awt.Dimension;
import javax.swing.JDialog;

/**
 *
 * @author ngocn
 */
public class Product extends javax.swing.JPanel {

    /**
     * Creates new form Product
     */
    
    public Product() {
        initComponents();
    }

    public JLabel getProductAdd() {
        return productAdd;
    }

    public JLabel getProductImg() {
        return productImg;
    }

    public void setTextProductName(String productName, String idCategory) {
        this.productName.setToolTipText(idCategory);
        this.productName.setText(productName);
    }

    public void setTextProductPrice(String productPrice) {
        this.productPrice.setText(productPrice);
    }
    
    public void setPriceL(String price) {
        this.productPrice.setName(price);
    }

    public void setTextProductDescription(String productName) {
        this.productDescription.setText(productName);
        this.productDescription.setToolTipText(productName);

    }

    public void setImage(String imgPath) {
        this.productImg.setToolTipText(imgPath);
        this.productImg.setIcon(new javax.swing.ImageIcon(getClass().getResource(imgPath)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        productImg = new javax.swing.JLabel();
        productAdd = new javax.swing.JLabel();
        productDescription = new javax.swing.JLabel();
        productDescriptionMore = new javax.swing.JLabel();
        productPrice = new javax.swing.JLabel();
        productName = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        productImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/products/cacao-sua-special-43851616127873.JPG"))); // NOI18N

        productAdd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        productAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/plus-1.png"))); // NOI18N
        productAdd.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(27, 43, 32), 1, true));
        productAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        productAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productAddMouseClicked(evt);
            }
        });

        productDescription.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        productDescription.setForeground(new java.awt.Color(153, 153, 153));
        productDescription.setText("Với vị Trà hảo hạng quyện cùng Sữa tạo nên sự kết hợp hài hòa, lôi cuốn. Truyền Thống lúc nào cũng là lựa chọn hàng đầu cho mọi cuộc gặp gỡ.");
        productDescription.setToolTipText("Với vị Trà hảo hạng quyện cùng Sữa tạo nên sự kết hợp hài hòa, lôi cuốn. Truyền Thống lúc nào cũng là lựa chọn hàng đầu cho mọi cuộc gặp gỡ.");

        productDescriptionMore.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        productDescriptionMore.setForeground(new java.awt.Color(153, 153, 153));
        productDescriptionMore.setText("xem thêm");
        productDescriptionMore.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        productDescriptionMore.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productDescriptionMoreMouseClicked(evt);
            }
        });

        productPrice.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        productPrice.setForeground(new java.awt.Color(27, 43, 32));
        productPrice.setText("₫23000");

        productName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        productName.setForeground(new java.awt.Color(0, 0, 0));
        productName.setText("Trà sữa Truyền Thống");
        productName.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(productImg, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(productName)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(productDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(productPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(productDescriptionMore, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(productAdd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(productName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productDescription)
                    .addComponent(productDescriptionMore))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(productPrice)
                    .addComponent(productAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addComponent(productImg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void productAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productAddMouseClicked
        CustomerDisplay customerDisplay = new CustomerDisplay();
        String priceM = productPrice.getText().split("₫")[1];
        String priceL = productPrice.getName();

        customerDisplay.getSelectProduct((String) productImg.getToolTipText(), priceM, priceL, (String) productName.getText(), (String) productDescription.getText());
    }//GEN-LAST:event_productAddMouseClicked

    private void productDescriptionMoreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productDescriptionMoreMouseClicked
        //JOptionPane.showMessageDialog(null, productDescription.getText(), "Mô tả sản phẩm", JOptionPane.PLAIN_MESSAGE);
        JFrame JFrame = new JFrame();
        Message message = new Message(JFrame, true);
        message.setTitle("Mô tả sản phẩm");
        message.setContent(productDescription.getText());
        message.setVisible(true);

    }//GEN-LAST:event_productDescriptionMoreMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel productAdd;
    private javax.swing.JLabel productDescription;
    private javax.swing.JLabel productDescriptionMore;
    private javax.swing.JLabel productImg;
    private javax.swing.JLabel productName;
    private javax.swing.JLabel productPrice;
    // End of variables declaration//GEN-END:variables
}
