/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.Customer;

import View.Customer.Notification.Warning;
import static View.Customer.CustomerDisplay.notification;
import static View.Customer.CustomerDisplay.SelectedToppings;
import static View.Customer.CustomerDisplay.total;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JCheckBox;
import javax.swing.JLabel;

/**
 *
 * @author ngocn
 */
public class Topping extends javax.swing.JPanel {

    int quantity;
    int priceTopping;

    public String toppingString;
    boolean check = false;

    /**
     * Creates new form Topping
     */
    public Topping() {
        initComponents();
        quantity = 0;
    }

    public int getQuantity() {
        return quantity;
    }

    public void setQuantity(String quantity) {
        this.quantity = Integer.parseInt(quantity);
        this.quantityTopping.setText(quantity);
    }

    public void checkQuantity() {
        if (quantity == 0) {
            minus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/minus-0-20px.png")));
        } else {
            minus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/minus-1-20px.png")));
        }
    }

    public String getTopping() {
        return toppingString;
    }

    public int getPriceTopping() {
        return priceTopping;
    }

    public void setPriceTopping(int priceTopping) {
        this.priceTopping = priceTopping;
    }

    public boolean getCheck() {
        return check;
    }

    public void setCheck(boolean check) {
        this.check = check;
    }

    public JLabel getPlus() {
        return plus;
    }

    public JLabel getMinus() {
        return minus;
    }

    public void setTopping(String topping, String price, String idTopping) {
        this.topping.setText("<html> <font color='#000000'>" + topping + "</font> <br><font color='#929492'>₫" + price + "</font> </html>");
        this.topping.setName(idTopping);
        toppingString = topping;
        setPriceTopping(Integer.parseInt(price));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topping = new javax.swing.JLabel();
        minus = new javax.swing.JLabel();
        quantityTopping = new javax.swing.JLabel();
        plus = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        topping.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        topping.setText("<html> <font color='#000000'>Nhỏ</font> <br><font color='#929492'>0đ </font> </html>");

        minus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/minus-0-20px.png"))); // NOI18N
        minus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minusMouseClicked(evt);
            }
        });

        quantityTopping.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        quantityTopping.setForeground(new java.awt.Color(0, 0, 0));
        quantityTopping.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quantityTopping.setText("0");

        plus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/plus-1-20px.png"))); // NOI18N
        plus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        plus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plusMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(topping, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                .addGap(89, 89, 89)
                .addComponent(minus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quantityTopping, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(plus)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(topping, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(plus)
                    .addComponent(quantityTopping)
                    .addComponent(minus))
                .addGap(14, 14, 14))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void plusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plusMouseClicked

        quantity++;
        quantityTopping.setText(String.valueOf(quantity));
        minus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/minus-1-20px.png")));

        Map<String, Integer> Topping = new HashMap<>();
        int idTopping = Integer.parseInt(topping.getName());
        Topping.put("idTopping", idTopping);
        Topping.put("quantity", quantity);

        for (int i = 0; i < SelectedToppings.size(); i++) {
            if (SelectedToppings.get(i).get("idTopping") == idTopping) {
                SelectedToppings.get(i).put("quantity", quantity);
                return;
            }
        }
        SelectedToppings.add(Topping);

    }//GEN-LAST:event_plusMouseClicked

    private void minusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minusMouseClicked

        if (quantity == 0) {
            notification.setAlwaysOnTop(true);
//            JOptionPane.showMessageDialog(notification, "Số lượng đã tối thiểu!!!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            Warning warning = new Warning(notification, true);
            warning.setTitle("Thông báo");
            warning.setWarning("Số lượng đã tối thiểu!!!");
            warning.setVisible(true);
            setCheck(false);
            return;
        }
        setCheck(true);
        if (quantity > 0) {
            quantity--;
            quantityTopping.setText(String.valueOf(quantity));

            int idTopping = Integer.parseInt(topping.getName());

            if (quantity == 0) {
                minus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/minus-0-20px.png")));
                for (int i = 0; i < SelectedToppings.size(); i++) {
                    if (SelectedToppings.get(i).get("idTopping") == idTopping) {
                        SelectedToppings.remove(i);
                        return;
                    }
                }
            }

            for (int i = 0; i < SelectedToppings.size(); i++) {
                if (SelectedToppings.get(i).get("idTopping") == idTopping) {
                    SelectedToppings.get(i).put("quantity", quantity);
                    return;
                }
            }
        }


    }//GEN-LAST:event_minusMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel minus;
    private javax.swing.JLabel plus;
    private javax.swing.JLabel quantityTopping;
    private javax.swing.JLabel topping;
    // End of variables declaration//GEN-END:variables
}
