/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.Employee;

import Controller.Employee.EditInfoEmployeeController;
import static Controller.LogRes.ManagerEmployee.Login.ManagerEmployee;
import static Controller.LogRes.ManagerEmployee.Register.encryptPassword;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class ChangePassEmployee extends javax.swing.JFrame {

    /**
     * Creates new form ChangePassEmployee
     */
    public ChangePassEmployee() {
        setUndecorated(true);
        setResizable(false);
        initComponents();
        iconHide1.setVisible(false);
        iconHide2.setVisible(false);
        iconHide3.setVisible(false);

        EchoCurrentPass.setVisible(false);
        EchoNewPass.setVisible(false);
        EchoReNewPass.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPasswordFieldCurrentPass = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        EchoCurrentPass = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPasswordFieldNewPass = new javax.swing.JPasswordField();
        EchoNewPass = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPasswordFieldReNewPass = new javax.swing.JPasswordField();
        EchoReNewPass = new javax.swing.JLabel();
        Xong = new javax.swing.JButton();
        iconShow1 = new javax.swing.JLabel();
        iconHide1 = new javax.swing.JLabel();
        iconHide2 = new javax.swing.JLabel();
        iconShow2 = new javax.swing.JLabel();
        iconHide3 = new javax.swing.JLabel();
        iconShow3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Đổi mật khẩu");
        setBounds(new java.awt.Rectangle(530, 140, 0, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPasswordFieldCurrentPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 64, 211, 35));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Mật khẩu hiện tại:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 14, 211, 38));

        EchoCurrentPass.setFont(new java.awt.Font("Segoe UI", 3, 10)); // NOI18N
        EchoCurrentPass.setForeground(new java.awt.Color(204, 0, 0));
        EchoCurrentPass.setText("jLabel2");
        jPanel1.add(EchoCurrentPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 105, 211, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Mật khẩu mới:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 125, 211, 38));
        jPanel1.add(jPasswordFieldNewPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 175, 211, 35));

        EchoNewPass.setFont(new java.awt.Font("Segoe UI", 3, 10)); // NOI18N
        EchoNewPass.setForeground(new java.awt.Color(204, 0, 0));
        EchoNewPass.setText("jLabel2");
        jPanel1.add(EchoNewPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 216, 211, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nhập lại mật khẩu mới:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 242, 211, 38));

        jPasswordFieldReNewPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldReNewPassActionPerformed(evt);
            }
        });
        jPanel1.add(jPasswordFieldReNewPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 292, 211, 35));

        EchoReNewPass.setFont(new java.awt.Font("Segoe UI", 3, 10)); // NOI18N
        EchoReNewPass.setForeground(new java.awt.Color(204, 0, 0));
        EchoReNewPass.setText("jLabel2");
        jPanel1.add(EchoReNewPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 333, 211, -1));

        Xong.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        Xong.setForeground(new java.awt.Color(0, 153, 153));
        Xong.setText("XONG");
        Xong.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 3));
        Xong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XongActionPerformed(evt);
            }
        });
        jPanel1.add(Xong, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 63, 33));

        iconShow1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/visible_24px.png"))); // NOI18N
        iconShow1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconShow1MouseClicked(evt);
            }
        });
        jPanel1.add(iconShow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, -1, 35));

        iconHide1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/hide_24px.png"))); // NOI18N
        iconHide1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconHide1MouseClicked(evt);
            }
        });
        jPanel1.add(iconHide1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, -1, 35));

        iconHide2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/hide_24px.png"))); // NOI18N
        iconHide2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconHide2MouseClicked(evt);
            }
        });
        jPanel1.add(iconHide2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, -1, 30));

        iconShow2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/visible_24px.png"))); // NOI18N
        iconShow2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconShow2MouseClicked(evt);
            }
        });
        jPanel1.add(iconShow2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 185, -1, 20));

        iconHide3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/hide_24px.png"))); // NOI18N
        iconHide3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconHide3MouseClicked(evt);
            }
        });
        jPanel1.add(iconHide3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 30, 40));

        iconShow3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/visible_24px.png"))); // NOI18N
        iconShow3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconShow3MouseClicked(evt);
            }
        });
        jPanel1.add(iconShow3, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 292, -1, 35));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/x_15px.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 20, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iconShow1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconShow1MouseClicked
        jPasswordFieldCurrentPass.setEchoChar((char) 0);
        iconHide1.setVisible(true);
        iconShow1.setVisible(false);

    }//GEN-LAST:event_iconShow1MouseClicked

    private void jPasswordFieldReNewPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldReNewPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldReNewPassActionPerformed

    private void iconHide1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconHide1MouseClicked
        jPasswordFieldCurrentPass.setEchoChar('*');
        iconHide1.setVisible(false);
        iconShow1.setVisible(true);
    }//GEN-LAST:event_iconHide1MouseClicked

    private void iconHide2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconHide2MouseClicked

        jPasswordFieldNewPass.setEchoChar('*');
        iconHide2.setVisible(false);
        iconShow2.setVisible(true);
    }//GEN-LAST:event_iconHide2MouseClicked

    private void iconShow2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconShow2MouseClicked

        jPasswordFieldNewPass.setEchoChar((char) 0);
        iconHide2.setVisible(true);
        iconShow2.setVisible(false);
    }//GEN-LAST:event_iconShow2MouseClicked

    private void iconShow3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconShow3MouseClicked

        jPasswordFieldReNewPass.setEchoChar((char) 0);
        iconHide3.setVisible(true);
        iconShow3.setVisible(false);
    }//GEN-LAST:event_iconShow3MouseClicked

    private void iconHide3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconHide3MouseClicked
        jPasswordFieldReNewPass.setEchoChar('*');
        iconHide3.setVisible(false);
        iconShow3.setVisible(true);
    }//GEN-LAST:event_iconHide3MouseClicked

    public static boolean check;
    private void XongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XongActionPerformed
        String pass = (String) ManagerEmployee.get("password");
        String encryptedPass = pass;

        char[] currentPasswordCharArray = jPasswordFieldCurrentPass.getPassword();
        String currentPass = encryptPassword(new String(currentPasswordCharArray));
        char[] newPasswordCharArray = jPasswordFieldNewPass.getPassword();
        String newPass = new String(newPasswordCharArray);
        char[] reNewPasswordCharArray = jPasswordFieldReNewPass.getPassword();
        String reNewPass = new String(reNewPasswordCharArray);
        System.out.println(currentPass);

        Integer id = (Integer) ManagerEmployee.get("idAccount");
        if (id == null) {
            JOptionPane.showMessageDialog(this, "Bạn cần đăng nhập để thao tác!!");
            return;
        }
        int idAccount = id;

        // Kiểm tra mật khẩu hiện tại
        if (currentPass.isEmpty()) {
            EchoCurrentPass.setText("Mật khẩu không được để trống!!!");
            EchoCurrentPass.setVisible(true);
        } else if (!encryptedPass.equals(currentPass)) {
            EchoCurrentPass.setText("Mật khẩu sai!!!");
            EchoCurrentPass.setVisible(true);
        } else {
            EchoCurrentPass.setVisible(false);
        }

        // Kiểm tra mật khẩu mới
        if (newPass.isEmpty()) {
            EchoNewPass.setText("Mật khẩu không được để trống!!!");
            EchoNewPass.setVisible(true);
        } else {
            // Kiểm tra độ phức tạp của mật khẩu mới bằng regex
            String passwordPattern = "^(?=.*[0-9])(?=.*[!@#$%^&*()_+\\-\\[\\]{}:;<>,.?/~`])[A-Za-z0-9!@#$%^&*()_+\\-\\[\\]{}:;<>,.?/~`]{6,}$";
            if (!newPass.matches(passwordPattern)) {
                EchoNewPass.setText("Phải có ít nhất 6 ký tự, chữ số, ký tự đặc biệt.");
                EchoNewPass.setVisible(true);
            } else {
                EchoNewPass.setVisible(false);
            }
        }

        // Kiểm tra xác nhận mật khẩu mới
        if (reNewPass.isEmpty()) {
            EchoReNewPass.setText("Mật khẩu không được để trống!!!");
            EchoReNewPass.setVisible(true);
        } else if (!newPass.equals(reNewPass)) {
            EchoReNewPass.setText("Mật khẩu không trùng khớp!!!");
            EchoReNewPass.setVisible(true);
        } else {
            EchoReNewPass.setVisible(false);
        }

        // Nếu tất cả các kiểm tra đều hợp lệ, tiến hành cập nhật mật khẩu
        if (!EchoCurrentPass.isVisible() && !EchoNewPass.isVisible() && !EchoReNewPass.isVisible()) {
            String encryptedNewPass = encryptPassword(newPass);
            boolean checkUpdate = EditInfoEmployeeController.updatePasswordEmployee(encryptedNewPass, idAccount);
            if (checkUpdate) {
                JOptionPane.showMessageDialog(this, "Sửa mật khẩu thành công!!");
                this.dispose();
                ManagerEmployee.put("password", newPass);
                System.out.println(encryptedNewPass);
            } else {
                JOptionPane.showMessageDialog(this, "Sửa mật khẩu thất bại!!");
            }
        }
    }//GEN-LAST:event_XongActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePassEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePassEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePassEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePassEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangePassEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EchoCurrentPass;
    private javax.swing.JLabel EchoNewPass;
    private javax.swing.JLabel EchoReNewPass;
    private javax.swing.JButton Xong;
    private javax.swing.JLabel iconHide1;
    private javax.swing.JLabel iconHide2;
    private javax.swing.JLabel iconHide3;
    private javax.swing.JLabel iconShow1;
    private javax.swing.JLabel iconShow2;
    private javax.swing.JLabel iconShow3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordFieldCurrentPass;
    private javax.swing.JPasswordField jPasswordFieldNewPass;
    private javax.swing.JPasswordField jPasswordFieldReNewPass;
    // End of variables declaration//GEN-END:variables
}
