/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.Employee;

import Controller.Employee.EditInfoEmployeeController;
import static Controller.LogRes.ManagerEmployee.Login.ManagerEmployee;
import static Controller.LogRes.ManagerEmployee.Login.getAccLogin;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author admin
 */
public class ChangeNumberPhoneEmployee extends javax.swing.JFrame {

    /**
     * Creates new form ChangeNumberPhoneEmployee
     */
    public ChangeNumberPhoneEmployee() {
         setUndecorated(true);
        setResizable(false);
        initComponents();
        thongBaoSoCuSai.setVisible(false);        
        thongBaoSoMoiSai.setVisible(false);
        getAccLogin((String) ManagerEmployee.get("userName"), true);
    }
    
    private boolean changeNumberPhoneEmployeeClosed = false;

    // Getter để trả về trạng thái của frame
    public boolean isChangeNumberPhoneEmployeeClosed() {
        return changeNumberPhoneEmployeeClosed;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        oldPhone = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        newPhone = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        thongBaoSoCuSai = new javax.swing.JLabel();
        thongBaoSoMoiSai = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Đổi số điện thoại");
        setBounds(new java.awt.Rectangle(450, 200, 0, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 51, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Số điện thoại hiện tại:");

        oldPhone.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Số điện thoại mới:");

        newPhone.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jButton1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 255));
        jButton1.setText("OK");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        thongBaoSoCuSai.setFont(new java.awt.Font("Segoe UI", 3, 10)); // NOI18N
        thongBaoSoCuSai.setForeground(new java.awt.Color(204, 0, 0));
        thongBaoSoCuSai.setText("jLabel3");

        thongBaoSoMoiSai.setFont(new java.awt.Font("Segoe UI", 3, 10)); // NOI18N
        thongBaoSoMoiSai.setForeground(new java.awt.Color(204, 0, 0));
        thongBaoSoMoiSai.setText("jLabel3");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/x_15px.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(thongBaoSoMoiSai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(thongBaoSoCuSai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(oldPhone)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(newPhone)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(75, 75, 75))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addContainerGap())))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(oldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(thongBaoSoCuSai)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(newPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(thongBaoSoMoiSai)
                .addGap(8, 8, 8)
                .addComponent(jButton1)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static boolean isValidPhoneNumber(String phoneNumber) {
        // Loại bỏ các ký tự không phải là số từ chuỗi số điện thoại
        String strippedNumber = phoneNumber.replaceAll("\\D", "");

        // Kiểm tra xem độ dài của chuỗi đã loại bỏ các ký tự không phải là số có phải là 10 không
        return strippedNumber.length() == 10;
    }
   
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       
        String users =(String)ManagerEmployee.get("userName");
        String pass =(String)ManagerEmployee.get("password");
        String numPhone =(String)ManagerEmployee.get("numberPhone");
        int idAccount;
        Integer id = (Integer) ManagerEmployee.get("idAccount");
        if (id== null) {
             JOptionPane.showMessageDialog(this, "Bạn cần đăng nhập để thao tác!!");
        } else {
           idAccount = id.intValue();
        
            System.out.println(users);
            System.out.println(pass);
            System.out.println(numPhone);
            String oldPhone = this.oldPhone.getText();
            String newPhone = this.newPhone.getText();
            System.out.println(oldPhone);
            
            if(oldPhone.isEmpty()){
                thongBaoSoCuSai.setVisible(true); 
                thongBaoSoCuSai.setText("Số điện thoại không được để trống!!");
            }else if(!oldPhone.isEmpty() && oldPhone.equals(numPhone)==false){
                thongBaoSoCuSai.setVisible(true);
                thongBaoSoCuSai.setText("Số điện thoại không trùng khớp!!");
            }else{
                 thongBaoSoCuSai.setVisible(false);
            }

            if(newPhone.isEmpty()){
            thongBaoSoMoiSai.setVisible(true); 
            thongBaoSoMoiSai.setText("Số điện thoại không được để trống!!");
            }else if(isValidPhoneNumber(newPhone)==false){
              thongBaoSoMoiSai.setVisible(true); 
              thongBaoSoMoiSai.setText("Số điện thoại phảo đủ 10 số!!");
            }else if(newPhone.equals(oldPhone)){
              thongBaoSoMoiSai.setVisible(true); 
              thongBaoSoMoiSai.setText("Số điện thoại không được giống số cũ!!");
            }
            else{
                thongBaoSoCuSai.setVisible(false);
                boolean check =EditInfoEmployeeController.checkNumberPhoneExist(newPhone);
                if(check==true){
                    thongBaoSoMoiSai.setVisible(true); 
                    thongBaoSoMoiSai.setText("Số điện thoại này đã tồn tại trong hệ thống!!");
                }else{
                    thongBaoSoCuSai.setVisible(false);        
                    boolean checkUpdate = EditInfoEmployeeController.updatePhoneEmployee(newPhone, idAccount);
                    if(checkUpdate==true){
                        thongBaoSoMoiSai.setVisible(false);
                        JOptionPane.showMessageDialog(this, "Sửa số điện thoại thành công!!");
                        this.dispose();
                        ManagerEmployee.put("numberPhone", newPhone);
                        changeNumberPhoneEmployeeClosed = true;
                    }else{
                        JOptionPane.showMessageDialog(this, "Sửa số điện thoại thất bại!!");
                         this.dispose();
                    }
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

     // Xử lý khi đóng frame bằng cách nhấn nút X
    private void formWindowClosing(java.awt.event.WindowEvent evt) {                                   
        // Đặt biến changeNumberPhoneEmployeeClosed thành true
        changeNumberPhoneEmployeeClosed = true;
    }   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangeNumberPhoneEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangeNumberPhoneEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangeNumberPhoneEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangeNumberPhoneEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangeNumberPhoneEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField newPhone;
    private javax.swing.JTextField oldPhone;
    private javax.swing.JLabel thongBaoSoCuSai;
    private javax.swing.JLabel thongBaoSoMoiSai;
    // End of variables declaration//GEN-END:variables
}
