/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.Employee;

import javax.swing.JLabel;
import javax.swing.JSpinner;

/**
 *
 * @author admin
 */
public class Item extends javax.swing.JPanel {

    /**
     * Creates new form Item
     */
    public Item() {
        initComponents();
    }

    public JLabel getAnh() {
        return anh;
    }

    public void setAnh(JLabel anh) {
        this.anh = anh;
    }

    public JLabel getChitiet() {
        return chitiet;
    }

    public void setChitiet(JLabel chitiet) {
        this.chitiet = chitiet;
    }

    public JSpinner getjSpinner1() {
        return jSpinner1;
    }

    public void setjSpinner1(JSpinner jSpinner1) {
        this.jSpinner1 = jSpinner1;
    }

    public JLabel getTenItem() {
        return tenItem;
    }

    public void setTenItem(JLabel tenItem) {
        this.tenItem = tenItem;
    }

    public JLabel getTentopping() {
        return tentopping;
    }

    public void setTentopping(JLabel tentopping) {
        this.tentopping = tentopping;
    }

    public JLabel getTongGiaItem() {
        return tongGiaItem;
    }

    public void setTongGiaItem(JLabel tongGiaItem) {
        this.tongGiaItem = tongGiaItem;
    }

    public JLabel getXoaItem() {
        return xoaItem;
    }

    public void setXoaItem(JLabel xoaItem) {
        this.xoaItem = xoaItem;
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tenItem = new javax.swing.JLabel();
        anh = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        tentopping = new javax.swing.JLabel();
        tongGiaItem = new javax.swing.JLabel();
        chitiet = new javax.swing.JLabel();
        xoaItem = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 51, 51));

        tenItem.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        tenItem.setForeground(new java.awt.Color(0, 204, 204));
        tenItem.setText("jLabel1");

        jSpinner1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        tentopping.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        tentopping.setForeground(new java.awt.Color(153, 153, 153));
        tentopping.setText("jLabel2");

        tongGiaItem.setBackground(new java.awt.Color(0, 102, 102));
        tongGiaItem.setFont(new java.awt.Font("Segoe UI", 3, 22)); // NOI18N
        tongGiaItem.setForeground(new java.awt.Color(204, 204, 0));
        tongGiaItem.setText("jLabel2");

        chitiet.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        chitiet.setForeground(new java.awt.Color(255, 255, 255));
        chitiet.setText("chi tiết");

        xoaItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/x_15px.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(anh, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tenItem, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(82, 82, 82)
                                .addComponent(xoaItem))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(tentopping, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(chitiet, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tongGiaItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tenItem, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(xoaItem, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tentopping, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(chitiet, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tongGiaItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(anh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anh;
    private javax.swing.JLabel chitiet;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel tenItem;
    private javax.swing.JLabel tentopping;
    private javax.swing.JLabel tongGiaItem;
    private javax.swing.JLabel xoaItem;
    // End of variables declaration//GEN-END:variables
}
