/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.Employee;

import Controller.Employee.CategoryController;
import Controller.Employee.DeleteProductController;
import Controller.Employee.GetMilkTeaFromDatabaseController;
import static Controller.LogRes.ManagerEmployee.Login.ManagerEmployee;
import javax.swing.JOptionPane;
import Model.Employee.getRowInTable;
/**
 *
 * @author admin
 */
public class ManageCategory extends javax.swing.JFrame {

    /**
     * Creates new form ManageCategory
     */
    public ManageCategory() {
        setResizable(false);
        setUndecorated(true);
        initComponents();
        jTableCategory.getColumnModel().getColumn(0).setPreferredWidth(300);       
        jTableCategory.getColumnModel().getColumn(1).setPreferredWidth(600);
        CategoryController.getListCategory(jTableCategory);
        
        EmployeeLogin.setText("NHÂN VIÊN:"+ManagerEmployee.get("fullName"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCategory = new javax.swing.JTable();
        jLabellogo = new javax.swing.JLabel();
        jLabelX = new javax.swing.JLabel();
        jButtonThem = new javax.swing.JButton();
        jButtonXoa = new javax.swing.JButton();
        jButtonSua = new javax.swing.JButton();
        EmployeeLogin = new javax.swing.JLabel();
        jPanelMainDM = new javax.swing.JPanel();
        jPanelClear = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanelThemDM = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButtonThemXong = new javax.swing.JButton();
        jButtonThemHuy = new javax.swing.JButton();
        jPanelSuaDM = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldSua = new javax.swing.JTextField();
        jButtonSuaHuy = new javax.swing.JButton();
        jButtonSuaXong = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản Lý Doanh Mục");
        setBackground(new java.awt.Color(0, 102, 102));
        setBounds(new java.awt.Rectangle(300, 150, 0, 0));
        setPreferredSize(new java.awt.Dimension(700, 410));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 380));

        jTableCategory.setBackground(new java.awt.Color(0, 102, 102));
        jTableCategory.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTableCategory.setForeground(new java.awt.Color(255, 255, 255));
        jTableCategory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã DOANH MỤC", "TÊN DOANH MỤC"
            }
        ));
        jTableCategory.setGridColor(new java.awt.Color(102, 102, 102));
        jTableCategory.setRowHeight(30);
        jTableCategory.setSelectionBackground(new java.awt.Color(0, 204, 204));
        jTableCategory.setSelectionForeground(new java.awt.Color(102, 102, 102));
        jTableCategory.setShowGrid(false);
        jTableCategory.setShowHorizontalLines(true);
        jTableCategory.setShowVerticalLines(true);
        jScrollPane1.setViewportView(jTableCategory);

        jLabellogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo38x35.jpg"))); // NOI18N
        jLabellogo.setText("jLabel2");

        jLabelX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/x_15px.png"))); // NOI18N
        jLabelX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelXMouseClicked(evt);
            }
        });

        jButtonThem.setBackground(new java.awt.Color(0, 102, 102));
        jButtonThem.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jButtonThem.setForeground(new java.awt.Color(255, 255, 255));
        jButtonThem.setText("THÊM");
        jButtonThem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jButtonThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThemActionPerformed(evt);
            }
        });

        jButtonXoa.setBackground(new java.awt.Color(0, 102, 102));
        jButtonXoa.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jButtonXoa.setForeground(new java.awt.Color(255, 255, 255));
        jButtonXoa.setText("XÓA");
        jButtonXoa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jButtonXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonXoaActionPerformed(evt);
            }
        });

        jButtonSua.setBackground(new java.awt.Color(0, 102, 102));
        jButtonSua.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jButtonSua.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSua.setText("SỬA");
        jButtonSua.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jButtonSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSuaActionPerformed(evt);
            }
        });

        EmployeeLogin.setFont(new java.awt.Font("SansSerif", 2, 18)); // NOI18N
        EmployeeLogin.setForeground(new java.awt.Color(153, 153, 153));
        EmployeeLogin.setText("QUẢN LÝ DOANH MỤC");

        jPanelMainDM.setForeground(new java.awt.Color(0, 102, 102));
        jPanelMainDM.setPreferredSize(new java.awt.Dimension(358, 200));
        jPanelMainDM.setLayout(new java.awt.CardLayout());

        jPanelClear.setBackground(new java.awt.Color(0, 102, 102));
        jPanelClear.setForeground(new java.awt.Color(0, 102, 102));
        jPanelClear.setPreferredSize(new java.awt.Dimension(358, 200));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cover-small.png"))); // NOI18N

        javax.swing.GroupLayout jPanelClearLayout = new javax.swing.GroupLayout(jPanelClear);
        jPanelClear.setLayout(jPanelClearLayout);
        jPanelClearLayout.setHorizontalGroup(
            jPanelClearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelClearLayout.setVerticalGroup(
            jPanelClearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelMainDM.add(jPanelClear, "card3");

        jPanelThemDM.setBackground(new java.awt.Color(0, 102, 102));
        jPanelThemDM.setForeground(new java.awt.Color(255, 255, 255));
        jPanelThemDM.setPreferredSize(new java.awt.Dimension(358, 200));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("THÊM DOANH MỤC");

        jTextField1.setBackground(new java.awt.Color(0, 102, 102));
        jTextField1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jButtonThemXong.setBackground(new java.awt.Color(0, 102, 102));
        jButtonThemXong.setFont(new java.awt.Font("Serif", 3, 16)); // NOI18N
        jButtonThemXong.setForeground(new java.awt.Color(255, 255, 255));
        jButtonThemXong.setText("Xong");
        jButtonThemXong.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jButtonThemXong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThemXongActionPerformed(evt);
            }
        });

        jButtonThemHuy.setBackground(new java.awt.Color(0, 102, 102));
        jButtonThemHuy.setFont(new java.awt.Font("Serif", 3, 16)); // NOI18N
        jButtonThemHuy.setForeground(new java.awt.Color(255, 255, 255));
        jButtonThemHuy.setText("Hủy");
        jButtonThemHuy.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jButtonThemHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThemHuyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelThemDMLayout = new javax.swing.GroupLayout(jPanelThemDM);
        jPanelThemDM.setLayout(jPanelThemDMLayout);
        jPanelThemDMLayout.setHorizontalGroup(
            jPanelThemDMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelThemDMLayout.createSequentialGroup()
                .addGroup(jPanelThemDMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelThemDMLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel1))
                    .addGroup(jPanelThemDMLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelThemDMLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonThemHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jButtonThemXong, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
        );
        jPanelThemDMLayout.setVerticalGroup(
            jPanelThemDMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelThemDMLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanelThemDMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonThemXong, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonThemHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        jPanelMainDM.add(jPanelThemDM, "card2");

        jPanelSuaDM.setBackground(new java.awt.Color(0, 102, 102));
        jPanelSuaDM.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("SỬA DOANH MỤC");

        jTextFieldSua.setBackground(new java.awt.Color(0, 102, 102));
        jTextFieldSua.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jTextFieldSua.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldSua.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jButtonSuaHuy.setBackground(new java.awt.Color(0, 102, 102));
        jButtonSuaHuy.setFont(new java.awt.Font("Serif", 3, 16)); // NOI18N
        jButtonSuaHuy.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSuaHuy.setText("Hủy");
        jButtonSuaHuy.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jButtonSuaHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSuaHuyActionPerformed(evt);
            }
        });

        jButtonSuaXong.setBackground(new java.awt.Color(0, 102, 102));
        jButtonSuaXong.setFont(new java.awt.Font("Serif", 3, 16)); // NOI18N
        jButtonSuaXong.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSuaXong.setText("Xong");
        jButtonSuaXong.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jButtonSuaXong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSuaXongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSuaDMLayout = new javax.swing.GroupLayout(jPanelSuaDM);
        jPanelSuaDM.setLayout(jPanelSuaDMLayout);
        jPanelSuaDMLayout.setHorizontalGroup(
            jPanelSuaDMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSuaDMLayout.createSequentialGroup()
                .addGroup(jPanelSuaDMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSuaDMLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jButtonSuaHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(jButtonSuaXong, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelSuaDMLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel4))
                    .addGroup(jPanelSuaDMLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jTextFieldSua, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanelSuaDMLayout.setVerticalGroup(
            jPanelSuaDMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSuaDMLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldSua, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanelSuaDMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSuaHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSuaXong, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanelMainDM.add(jPanelSuaDM, "card4");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelX)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabellogo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jPanelMainDM, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jButtonThem, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonSua, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(EmployeeLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelX, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanelMainDM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonThem, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSua, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabellogo)
                    .addComponent(EmployeeLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelXMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabelXMouseClicked

    private void jButtonThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThemActionPerformed
        // TODO add your handling code here:
        changePanelThemDM();
    }//GEN-LAST:event_jButtonThemActionPerformed

    private void jButtonThemXongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThemXongActionPerformed
        // TODO add your handling code here:
        int opt = JOptionPane.showConfirmDialog(this, "Bạn muốn thêm doanh mục mới?", "Xác nhận", JOptionPane.YES_NO_OPTION);
       if(opt==JOptionPane.YES_OPTION){
            String nameCategory = jTextField1.getText();
        boolean check = CategoryController.addCategory(nameCategory);
        if(check==true){
            JOptionPane.showMessageDialog(this, "Thêm doanh mục thành công!");
            changePanelClear();
        }else{
            JOptionPane.showMessageDialog(this, "Thêm doanh mục thất bại!");
        }
        CategoryController.getListCategory(jTableCategory);
       }
    }//GEN-LAST:event_jButtonThemXongActionPerformed

    private void jButtonThemHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThemHuyActionPerformed
        // TODO add your handling code here:
        int opt = JOptionPane.showConfirmDialog(this, "Bạn muốn hủy thêm doanh mục mới?", "Xác nhận", JOptionPane.YES_NO_OPTION);
          if(opt==JOptionPane.YES_OPTION){
              changePanelClear();
          }
             
    }//GEN-LAST:event_jButtonThemHuyActionPerformed

    private void jButtonXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXoaActionPerformed
          int[] rows = getRowInTable.getRows(jTableCategory);
        if (rows.length == 0 || rows[0] == -1) {
            // Nếu không có dòng nào được chọn, hiển thị thông báo và kết thúc hàm
            changePanelClear();
            JOptionPane.showMessageDialog(this, "Vui lòng chọn dòng thức uống cần xóa!");
            return;
        }

        // Xác nhận người dùng muốn xóa
        int option = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa?", "Xác nhận xóa", JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.YES_OPTION) {
            boolean success = false; // Biến để kiểm tra xem có xóa thành công ít nhất một dòng hay không
            // Người dùng chọn "Yes", thực hiện xóa
            for (int row : rows) {
                int idCategory = Integer.parseInt(jTableCategory.getValueAt(row, 0).toString());
                boolean check = CategoryController.deleteCategory(idCategory);
                if (check == true) {
                    success = true; // Đã xóa thành công ít nhất một dòng
                } else {
                    JOptionPane.showMessageDialog(this, "Có lỗi xảy ra!!");
                }
            }

            if (success) {
               JOptionPane.showMessageDialog(this, "Đã xóa thành công!!");
               CategoryController.getListCategory(jTableCategory);
               
               changePanelClear();
            }
        }
        
    }//GEN-LAST:event_jButtonXoaActionPerformed

    private void jButtonSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSuaActionPerformed
        // TODO add your handling code here:
        changePanelSuaDM();
         // Lấy dòng đã chọn từ jTableTS
        int rowSelected = jTableCategory.getSelectedRow();
        if (rowSelected == -1) {
            // Xử lý khi không có dòng nào được chọn
            changePanelClear();
            JOptionPane.showMessageDialog(this, "Vui lòng chọn dòng thức uống cần sửa");
            return;
        }

        // Lấy idProductDetail từ dòng đã chọn
        int idCategory= Integer.parseInt(jTableCategory.getValueAt(rowSelected, 0).toString());
        String nameCategory =jTableCategory.getValueAt(rowSelected, 1).toString();
        jTextFieldSua.setText(nameCategory);
    }//GEN-LAST:event_jButtonSuaActionPerformed

    private void jButtonSuaHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSuaHuyActionPerformed
        // TODO add your handling code here:
          int opt = JOptionPane.showConfirmDialog(this, "Bạn muốn hủy sửa doanh mục ?", "Xác nhận", JOptionPane.YES_NO_OPTION);
          if(opt==JOptionPane.YES_OPTION){
              changePanelClear();
              jTextFieldSua.setText("");
          }
        
    }//GEN-LAST:event_jButtonSuaHuyActionPerformed

    private void jButtonSuaXongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSuaXongActionPerformed
        // TODO add your handling code here:
         changePanelSuaDM();
         // Lấy dòng đã chọn từ jTableTS
        int rowSelected = jTableCategory.getSelectedRow();
        if (rowSelected == -1) {
            // Xử lý khi không có dòng nào được chọn
            changePanelClear();
            JOptionPane.showMessageDialog(this, "Vui lòng chọn dòng thức uống cần sửa");
            return;
        }

        // Lấy idProductDetail từ dòng đã chọn
        int idCategory= Integer.parseInt(jTableCategory.getValueAt(rowSelected, 0).toString());
        String newNameCategory = jTextFieldSua.getText();
        int opt= JOptionPane.showConfirmDialog(this, "Bạn chắc chắn muốn sửa doanh mục này?","Xác nhận sửa",JOptionPane.YES_NO_OPTION);
        if(opt==JOptionPane.YES_OPTION){
            boolean check = CategoryController.updateCategory(newNameCategory, idCategory);
            if(check==true){
                JOptionPane.showMessageDialog(this, "Sửa tên doanh mục thành công!");
            }else{
            JOptionPane.showMessageDialog(this, "Sửa tên doanh mục thất bại!");
            }
            CategoryController.getListCategory(jTableCategory);
            changePanelClear();
        }
    }//GEN-LAST:event_jButtonSuaXongActionPerformed

    
    public void changePanelThemDM(){
        this.jPanelMainDM.removeAll();
        this.jPanelMainDM.add(this.jPanelThemDM);
        this.jPanelMainDM.repaint();
        this.jPanelMainDM.revalidate();
    }
    
    public void changePanelSuaDM(){
        this.jPanelMainDM.removeAll();
        this.jPanelMainDM.add(this.jPanelSuaDM);
        this.jPanelMainDM.repaint();
        this.jPanelMainDM.revalidate();
    }
    
     public void changePanelClear(){
        this.jPanelMainDM.removeAll();
        this.jPanelMainDM.add(this.jPanelClear);
        this.jPanelMainDM.repaint();
        this.jPanelMainDM.revalidate();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageCategory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EmployeeLogin;
    private javax.swing.JButton jButtonSua;
    private javax.swing.JButton jButtonSuaHuy;
    private javax.swing.JButton jButtonSuaXong;
    private javax.swing.JButton jButtonThem;
    private javax.swing.JButton jButtonThemHuy;
    private javax.swing.JButton jButtonThemXong;
    private javax.swing.JButton jButtonXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelX;
    private javax.swing.JLabel jLabellogo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelClear;
    private javax.swing.JPanel jPanelMainDM;
    private javax.swing.JPanel jPanelSuaDM;
    private javax.swing.JPanel jPanelThemDM;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCategory;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldSua;
    // End of variables declaration//GEN-END:variables
}
