/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.Employee;


import javax.swing.JLabel;

/**
 *
 * @author admin
 */
public class OneLineBill extends javax.swing.JPanel {

    /**
     * Creates new form HoaDonPanel
     */
    public OneLineBill() {
        initComponents();
        
    }

    public JLabel getThanhTien() {
        return ThanhTien;
    }

    public void setThanhTien(JLabel ThanhTien) {
        this.ThanhTien = ThanhTien;
    }

    public JLabel getThem() {
        return Them;
    }

    public void setThem(JLabel Them) {
        this.Them = Them;
    }

    public JLabel getGia() {
        return gia;
    }

    public void setGia(JLabel gia) {
        this.gia = gia;
    }

    public JLabel getSoluong() {
        return soluong;
    }

    public void setSoluong(JLabel soluong) {
        this.soluong = soluong;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Them = new javax.swing.JLabel();
        soluong = new javax.swing.JLabel();
        gia = new javax.swing.JLabel();
        ThanhTien = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        Them.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        Them.setForeground(new java.awt.Color(0, 0, 0));
        Them.setText("ten");

        soluong.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        soluong.setForeground(new java.awt.Color(0, 0, 0));
        soluong.setText("sl");

        gia.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        gia.setForeground(new java.awt.Color(0, 0, 0));
        gia.setText("gia");

        ThanhTien.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        ThanhTien.setForeground(new java.awt.Color(0, 0, 0));
        ThanhTien.setText("TT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Them, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(soluong, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gia, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(soluong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Them, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(gia, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(ThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ThanhTien;
    private javax.swing.JLabel Them;
    private javax.swing.JLabel gia;
    private javax.swing.JLabel soluong;
    // End of variables declaration//GEN-END:variables
}
