/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.Employee;

import javax.swing.JLabel;
import javax.swing.JSpinner;

/**
 *
 * @author admin
 */
public class ReViewTopping extends javax.swing.JPanel {

    /**
     * Creates new form ReChooseProduct
     */
    public ReViewTopping() {
        initComponents();
    }

    public JLabel getAnhTopping() {
        return anhTopping;
    }

    public void setAnhTopping(JLabel anhTopping) {
        this.anhTopping = anhTopping;
    }

    public JLabel getGiaTopping() {
        return giaTopping;
    }

    public void setGiaTopping(JLabel giaTopping) {
        this.giaTopping = giaTopping;
    }

    public JSpinner getjSpinnerSLTP() {
        return jSpinnerSLTP;
    }

    public void setjSpinnerSLTP(JSpinner jSpinnerSLTP) {
        this.jSpinnerSLTP = jSpinnerSLTP;
    }

    public JLabel getTenTopping() {
        return tenTopping;
    }

    public void setTenTopping(JLabel tenTopping) {
        this.tenTopping = tenTopping;
    }

   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        anhTopping = new javax.swing.JLabel();
        tenTopping = new javax.swing.JLabel();
        giaTopping = new javax.swing.JLabel();
        jSpinnerSLTP = new javax.swing.JSpinner();

        setBackground(new java.awt.Color(255, 255, 255));

        anhTopping.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tenTopping.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        tenTopping.setForeground(new java.awt.Color(0, 0, 0));
        tenTopping.setText("jLabel1");

        giaTopping.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        giaTopping.setForeground(new java.awt.Color(204, 204, 0));
        giaTopping.setText("jLabel1");

        jSpinnerSLTP.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jSpinnerSLTP.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(anhTopping, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tenTopping, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(52, 52, 52))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(giaTopping, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jSpinnerSLTP, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tenTopping, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(giaTopping, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinnerSLTP, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(anhTopping, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anhTopping;
    private javax.swing.JLabel giaTopping;
    private javax.swing.JSpinner jSpinnerSLTP;
    private javax.swing.JLabel tenTopping;
    // End of variables declaration//GEN-END:variables
}
