/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.Employee;

import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author admin
 */
public class StatusBill extends javax.swing.JPanel {

    /**
     * Creates new form StatusBill
     */
    public StatusBill() {
        initComponents();
    }

    public JLabel getMaHD() {
        return MaHD;
    }

    public void setMaHD(JLabel MaHD) {
        this.MaHD = MaHD;
    }

    public JLabel getNgayHD() {
        return NgayHD;
    }

    public void setNgayHD(JLabel NgayHD) {
        this.NgayHD = NgayHD;
    }

    public JLabel getStatusHD() {
        return StatusHD;
    }

    public void setStatusHD(JLabel StatusHD) {
        this.StatusHD = StatusHD;
    }

    public JButton getStatusHuy() {
        return StatusHuy;
    }

    public void setStatusHuy(JButton StatusHuy) {
        this.StatusHuy = StatusHuy;
    }

    public JButton getStatusXacNhan() {
        return StatusXacNhan;
    }

    public void setStatusXacNhan(JButton StatusXacNhan) {
        this.StatusXacNhan = StatusXacNhan;
    }

    public JButton getXUATHD() {
        return XUATHD;
    }

    public void setXUATHD(JButton XUATHD) {
        this.XUATHD = XUATHD;
    }

    public JLabel getChiTietHD() {
        return chiTietHD;
    }

    public void setChiTietHD(JLabel chiTietHD) {
        this.chiTietHD = chiTietHD;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MaHD = new javax.swing.JLabel();
        StatusHD = new javax.swing.JLabel();
        NgayHD = new javax.swing.JLabel();
        StatusXacNhan = new javax.swing.JButton();
        StatusHuy = new javax.swing.JButton();
        XUATHD = new javax.swing.JButton();
        chiTietHD = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        MaHD.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        MaHD.setForeground(new java.awt.Color(0, 0, 0));
        MaHD.setText("MaHD");

        StatusHD.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        StatusHD.setForeground(new java.awt.Color(0, 0, 0));
        StatusHD.setText("Trạng thái");

        NgayHD.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        NgayHD.setForeground(new java.awt.Color(0, 0, 0));
        NgayHD.setText("Ngay");

        StatusXacNhan.setBackground(new java.awt.Color(255, 255, 255));
        StatusXacNhan.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        StatusXacNhan.setForeground(new java.awt.Color(0, 153, 153));
        StatusXacNhan.setText("XÁC NHẬN");
        StatusXacNhan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 2));

        StatusHuy.setBackground(new java.awt.Color(255, 255, 255));
        StatusHuy.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        StatusHuy.setForeground(new java.awt.Color(255, 0, 0));
        StatusHuy.setText("HỦY");
        StatusHuy.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 102), 2));

        XUATHD.setBackground(new java.awt.Color(255, 255, 255));
        XUATHD.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        XUATHD.setForeground(new java.awt.Color(0, 0, 0));
        XUATHD.setText("XUẤT HĐ");
        XUATHD.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        chiTietHD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chiTietHD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/info_32px.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MaHD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NgayHD, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(StatusHD, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StatusXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StatusHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(XUATHD, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chiTietHD, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(StatusXacNhan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(XUATHD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chiTietHD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(StatusHD, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MaHD, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NgayHD, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(StatusHuy, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MaHD;
    private javax.swing.JLabel NgayHD;
    private javax.swing.JLabel StatusHD;
    private javax.swing.JButton StatusHuy;
    private javax.swing.JButton StatusXacNhan;
    private javax.swing.JButton XUATHD;
    private javax.swing.JLabel chiTietHD;
    // End of variables declaration//GEN-END:variables
}
