/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View.Customer.Notification;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JLayeredPane;
import static View.Customer.CustomerDisplay.invisibleFrame;

/**
 *
 * @author ngocn
 */
public class Warning extends javax.swing.JDialog {

    /**
     * Creates new form NewJDialog
     */
    boolean x = false, y = false;

    public Warning(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        setUndecorated(true);
        setResizable(false);
        initComponents();
        setLocationRelativeTo(null);
        
        x = false; y = false;
        if (!invisibleFrame.isVisible()) {
            x = true;
            invisibleFrame.setUndecorated(true);
            invisibleFrame.setSize(new java.awt.Dimension(621, 1344));
            invisibleFrame.setBackground(new Color(0, 0, 0, 60));
            invisibleFrame.setUndecorated(true);
            invisibleFrame.setResizable(false);
            invisibleFrame.setLocationRelativeTo(null);
            invisibleFrame.setVisible(true);
            invisibleFrame.setAlwaysOnTop(true);
        } else {
            x = false;
            invisibleFrame.setAlwaysOnTop(true);
        }
        continueBtn.setText("");
        continueBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        continueBtn.setEnabled(false);
        cancel.setText("");
        cancel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        cancel.setEnabled(false);
        
        setAlwaysOnTop(true);
    }

    public Warning(java.awt.Frame parent, boolean modal, boolean something) {
        super(parent, modal);
        setUndecorated(true);
        setResizable(false);
        initComponents();
        setLocationRelativeTo(null);

        x = false; y = false;
        if (!invisibleFrame.isVisible()) {
            x = true;
            invisibleFrame.setUndecorated(true);
            invisibleFrame.setSize(new java.awt.Dimension(621, 1344));
            invisibleFrame.setBackground(new Color(0, 0, 0, 60));
            invisibleFrame.setUndecorated(true);
            invisibleFrame.setResizable(false);
            invisibleFrame.setLocationRelativeTo(null);
            invisibleFrame.setAlwaysOnTop(true);
            invisibleFrame.setVisible(true);
        } else {
            x = false;
            invisibleFrame.setAlwaysOnTop(true);
        }

        close.setVisible(false);
        setAlwaysOnTop(true);
    }

    public void setInvisibleOnTop() {
        invisibleFrame.setAlwaysOnTop(true);
    }

    public void setWarning(String text) {
        this.warning.setText(text);
    }
    
    public void setColorWarning() {
        warning.setForeground(new java.awt.Color(0, 150, 0));
    } 

    public void setTitle(String text) {
        this.title.setText(text);
    }

    public boolean getConfirm() {
        return y;
    }

    public void setConfirm(boolean y) {
        this.y = y;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        warning = new javax.swing.JLabel();
        continueBtn = new javax.swing.JLabel();
        cancel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.setPreferredSize(new java.awt.Dimension(621, 110));

        title.setBackground(new java.awt.Color(210, 154, 95));
        title.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        title.setForeground(new java.awt.Color(0, 0, 0));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Thông báo");

        close.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        close.setForeground(new java.awt.Color(0, 0, 0));
        close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close.setText("Xác nhận");
        close.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
        });

        warning.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        warning.setForeground(new java.awt.Color(255, 0, 0));
        warning.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        warning.setText("jLabel1");

        continueBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        continueBtn.setForeground(new java.awt.Color(0, 0, 0));
        continueBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        continueBtn.setText("Tiếp tục");
        continueBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 150, 0), 1, true));
        continueBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        continueBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                continueBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                continueBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                continueBtnMouseExited(evt);
            }
        });

        cancel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cancel.setForeground(new java.awt.Color(0, 0, 0));
        cancel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cancel.setText("Hủy");
        cancel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, true));
        cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 138, Short.MAX_VALUE)
                        .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(continueBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(warning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(warning)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(continueBtn)
                        .addComponent(cancel))
                    .addComponent(close))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        dispose();
        if (x) {
            invisibleFrame.setAlwaysOnTop(false);
            invisibleFrame.dispose();
        } else {
            invisibleFrame.setAlwaysOnTop(false);
        }
        setConfirm(true);
    }//GEN-LAST:event_closeMouseClicked

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
        close.setForeground(new Color(0, 150, 0));
    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
        close.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_closeMouseExited

    private void continueBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_continueBtnMouseClicked
        dispose();
        if (x) {
            invisibleFrame.setAlwaysOnTop(false);
            invisibleFrame.dispose();
        } else {
            invisibleFrame.setAlwaysOnTop(false);
        }
        setConfirm(true);
    }//GEN-LAST:event_continueBtnMouseClicked

    private void continueBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_continueBtnMouseEntered
        continueBtn.setForeground(new Color(0, 150, 0));
    }//GEN-LAST:event_continueBtnMouseEntered

    private void continueBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_continueBtnMouseExited
        continueBtn.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_continueBtnMouseExited

    private void cancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseEntered
        cancel.setForeground(new Color(255, 0, 0));
    }//GEN-LAST:event_cancelMouseEntered

    private void cancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseExited
        cancel.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_cancelMouseExited

    private void cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseClicked
        dispose();
        if (x) {
            invisibleFrame.setAlwaysOnTop(false);
            invisibleFrame.dispose();
        } else {
            invisibleFrame.setAlwaysOnTop(false);
        }
        setConfirm(false);
    }//GEN-LAST:event_cancelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Warning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Warning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Warning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Warning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Warning dialog = new Warning(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cancel;
    private javax.swing.JLabel close;
    private javax.swing.JLabel continueBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel title;
    private javax.swing.JLabel warning;
    // End of variables declaration//GEN-END:variables
}
